name: uwdart
version: 0.0.1
description: >-
  Waterloo OpenData Client in Dart. Allows you to access
  data provided by Waterloo Open Data for your application.
author: Deep Dhillon <deep@deepdhillon.ca>
dependencies:
  http: "^0.11.3+16"
